<a href="https://colab.research.google.com/github/Chandana472/-AP19110010369-_CSE306L/blob/main/ML_ASSIGNMENT(1)_AP19110010369_CSE(C)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##Write a python program to create a random array and compute the Covariance Matrix and Correlation Matrix.

In [ ]:
import numpy as np
import random
n=int(input("Enter the size of arrays:"))
array1 = np.random.randint(1000,size=(n,n))
array2=np.random.randint(1000,size=(n,n))
print(array1)
print(array2)

Enter the size of arrays:2
[[546 158]
 [344 359]]
[[132  34]
 [462 226]]


In [ ]:
##Variance of array1
var=np.var(array1)
print(var)

18846.1875


In [ ]:
##Variance of array2
var2=np.var(array2)
print(var2)

25192.75


In [ ]:
def cov(array1, array2):

    if len(array1) != len(array2):
        return

    array1_mean = np.mean(array1)
    array2_mean = np.mean(array2)

    sum = 0

    for i in range(0, len(array1)):
        sum = np.sum((array1[i] - array1_mean) * (array2[i] - array2_mean))/(len(array1)-1)##using mean to find covariance
    return (sum)
a=cov(array1,array2)
print(a)

-1835.25


In [ ]:
##Covariance Matrix
Cov=np.array([[var,a],[a,var2]])
print(Cov)

[[18846.1875 -1835.25  ]
 [-1835.25   25192.75  ]]


In [ ]:
##Correlation Matrix
Corr=Cov/(array1.std()*array2.std())
print(Corr)

[[ 0.86491607 -0.08422591]
 [-0.08422591  1.15618155]]


In [ ]:
###2)Write a python program to create a random array and compute Euclidian distance between every data point.

In [ ]:
import numpy as np
n=int(input("Enter number of elements in the array:"))
array1=np.random.randint(1000,size=n)
array2=np.random.randint(1000,size=n)
d=0
def euclidean_distance(array1,array2):
    for i in range(0, len(array1)):
        for j in range(0,len(array2)):
            d = np.sqrt(sum((array1-array2)**2))
            return (d)
print(euclidean_distance(array1,array2))

Enter number of elements in the array:3
793.1714820894659


In [ ]:
##With linalg.norm of numpy
dist = np.linalg.norm(array1-array2)
print(dist)

793.1714820894659
